In [ ]:
# Спринт 2/11: 2 спринт. Улучшение baseline-модели → Тема 3/6: Feature engineering —
# генерация и отбор признаков → Урок 4/11

# Работа с различными типами признаков

In [30]:
import pandas as pd
import numpy as np
from datetime import timedelta
from sklearn.preprocessing import Binarizer, StandardScaler, LabelEncoder

In [31]:
np.random.seed(42)
np.random.default_rng(42)

Generator(PCG64) at 0x7F60B3ACD8C0

In [32]:
# генерация данных для каждого столбца
data = {
    'temperature_celsius': np.random.uniform(20, 35, size=100),  # температура в градусах Цельсия (float)
    'age_years': np.random.randint(18, 65, size=100),  # возраст в годах (int)
    'timestamp_event': [pd.Timestamp('20230101') + timedelta(days=i) for i in range(100)],  # время события (datetime)
    'product_category': np.random.choice(['electronics', 'clothing', 'food'], size=100),  # категория продукта (string)
    'is_purchased': np.random.choice([True, False], size=100),  # булевое значение приобретения (bool)
    'humidity_percentage': np.random.uniform(40, 80, size=100),  # влажность в процентах (float)
    'income_usd': np.random.randint(20000, 100000, size=100),  # доход в долларах США (int)
    'last_updated': [pd.Timestamp('20240101') + timedelta(days=i) for i in range(100)],  # последнее обновление (datetime)
    'product_name': ['Product_' + str(i) for i in range(100)],  # название продукта (string)
    'is_subscribed': np.random.choice([True, False], size=100)  # булевое значение подписки (bool)
}


In [33]:
# создание DataFrame
df = pd.DataFrame(data)
df.head()

temperature_celsius  age_years timestamp_event product_category   
0            25.618102         49      2023-01-01      electronics  \
1            34.260715         56      2023-01-02      electronics   
2            30.979909         49      2023-01-03             food   
3            28.979877         21      2023-01-04         clothing   
4            22.340280         47      2023-01-05      electronics   

   is_purchased  humidity_percentage  income_usd last_updated product_name   
0          True            47.775201       75069   2024-01-01    Product_0  \
1          True            56.454156       34397   2024-01-02    Product_1   
2         False            67.980488       61555   2024-01-03    Product_2   
3          True            45.534124       66959   2024-01-04    Product_3   
4          True            45.309817       20728   2024-01-05    Product_4   

   is_subscribed  
0          False  
1           True  
2           True  
3           True  
4           True

In [39]:
# ваш код здесь #
df['income_usd_binarized'] = Binarizer(threshold=df['income_usd'].mean()).fit_transform(np.array(df['income_usd']).reshape(1, -1)).reshape(-1,1)
df['age_years_standarded'] = StandardScaler().fit_transform(np.array(df['age_years']).reshape(1, -1)).reshape(-1,1)
df['is_subscribed_encoded'] = LabelEncoder().fit_transform(df['is_subscribed'])

In [41]:
df.head()

temperature_celsius  age_years timestamp_event product_category   
0            25.618102         49      2023-01-01      electronics  \
1            34.260715         56      2023-01-02      electronics   
2            30.979909         49      2023-01-03             food   
3            28.979877         21      2023-01-04         clothing   
4            22.340280         47      2023-01-05      electronics   

   is_purchased  humidity_percentage  income_usd last_updated product_name   
0          True            47.775201       75069   2024-01-01    Product_0  \
1          True            56.454156       34397   2024-01-02    Product_1   
2         False            67.980488       61555   2024-01-03    Product_2   
3          True            45.534124       66959   2024-01-04    Product_3   
4          True            45.309817       20728   2024-01-05    Product_4   

   is_subscribed  income_usd_binarized  age_years_standarded   
0          False                     1                   0.0  \
1           True                     0                   0.0   
2           True                     1                   0.0   
3           True                     1                   0.0   
4           True                     0                   0.0   

   is_subscribed_encoded  
0                      0  
1                      1  
2                      1  
3                      1  
4                      1

In [36]:
from sklearn.preprocessing import StandardScaler
import numpy as np

X_train = np.array([[ 1., -1.,  2.],
[ 2.,  0.,  0.],
[ 0.,  1., -1.]])

transformer = StandardScaler().fit(X_train) # оцениваем параметры модели
transformer.mean_ # получаем средние значения для преобразования
transformer.scale_ # получаем масштабы для преобразования

X_scaled = transformer.transform(X_train) # применяем преобразование к данным
X_scaled # получаем преобразованные данные 

array([[ 0.        , -1.22474487,  1.33630621],
       [ 1.22474487,  0.        , -0.26726124],
       [-1.22474487,  1.22474487, -1.06904497]])

In [48]:
test = np.array(df['age_years'].astype('float')).reshape(1, -1)
test

array([[49., 56., 49., 21., 47., 54., 40., 56., 62., 32., 60., 46., 53.,
        30., 49., 24., 39., 45., 19., 59., 62., 23., 45., 45., 61., 61.,
        37., 47., 28., 45., 42., 56., 50., 18., 44., 30., 58., 20., 56.,
        23., 25., 44., 26., 54., 50., 59., 61., 41., 32., 49., 49., 41.,
        58., 29., 56., 19., 20., 54., 34., 19., 19., 45., 40., 54., 49.,
        50., 18., 36., 19., 61., 43., 49., 23., 49., 21., 28., 34., 55.,
        41., 22., 51., 23., 39., 28., 33., 50., 26., 23., 33., 46., 20.,
        37., 53., 36., 43., 20., 36., 37., 49., 24.]])

In [51]:
sts = StandardScaler().fit(test, sample_weight=None)

In [52]:
trf = sts.transform(test)
trf

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0.]])

In [3]:
# Пример использования: если у вас есть признак «Тип автомобиля» с категориями «Седан», 
# «Хэтчбек», «Универсал», то OneHotEncoder поможет преобразовать его в бинарные столбцы, 
# чтобы использовать в моделях машинного обучения.

from sklearn.preprocessing import OneHotEncoder
import numpy as np

data = np.array(['Универсал', 'Седан', 'Универсал', 'Хэтчбек']).reshape(-1, 1)
encoder = OneHotEncoder()
encoded_data = encoder.fit_transform(data).toarray()
encoded_data

array([[0., 1., 0.],
       [1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [4]:
data

array([['Универсал'],
       ['Седан'],
       ['Универсал'],
       ['Хэтчбек']], dtype='<U9')

In [ ]:
# Пример использования: в финансовом анализе для оценки временных рядов (например, 
# прогнозирования курсов валют) — с помощью сплайнов можно генерировать гладкие кривые, 
# чтобы проследить изменения данных во времени.

from sklearn.preprocessing import SplineTransformer
import numpy as np

X = np.random.rand(10, 1)
transformer = SplineTransformer(n_knots=3, degree=2)
X_transformed = transformer.fit_transform(X)
X_transformed

# Этот энкодер создаёт новую матрицу признаков, состоящую из сплайнов порядка degree. 
# Количество сгенерированных сплайнов равно n_splines=n_knots + degree - 1 для каждого признака, где
# n_knots определяет количество узлов (точек, в которых сопрягаются сплайны) для каждого признака. 
# Он указывает, сколько понадобится точек, чтобы разбить признак на интервалы. В этих интервалах сплайны
# будут аппроксимировать данные.
# degree определяет порядок полинома, используемого для построения сплайнов. Это число указывает степень 
# полинома, применяемого для каждого сплайна.

array([[0.39705082, 0.59702217, 0.00592701, 0.        ],
       [0.        , 0.        , 0.5       , 0.5       ],
       [0.18518327, 0.73821093, 0.0766058 , 0.        ],
       [0.        , 0.32465383, 0.65648863, 0.01885754],
       [0.39499097, 0.59882734, 0.00618169, 0.        ],
       [0.02090421, 0.66266267, 0.31643312, 0.        ],
       [0.5       , 0.5       , 0.        , 0.        ],
       [0.0310646 , 0.68712809, 0.28180731, 0.        ],
       [0.12124462, 0.74994272, 0.12881265, 0.        ],
       [0.        , 0.00143023, 0.55062282, 0.44794694]])

In [7]:
# QuantileTransformer (квантильное преобразование)
# Этот метод преобразует признаки, чтобы они распределялись равномерно или нормально — 
# так данные меньше подвергаются влиянию выбросов. Преобразование применяется к каждому 
# признаку независимо. Идея метода такова: оценить функцию распределения признака, чтобы 
# преобразовать исходные значения в равномерное распределение. 
# Пример использования: если у вас есть данные о доходах с широким диапазоном значений, 
# квантильное преобразование сделает их более сопоставимыми и устойчивыми к выбросам.

from sklearn.preprocessing import QuantileTransformer
import numpy as np

X = np.random.rand(10, 1)
transformer = QuantileTransformer()
X_transformed = transformer.fit_transform(X)
X

/home/mle-user/.local/lib/python3.10/site-packages/sklearn/preprocessing/_data.py:2762: UserWarning: n_quantiles (1000) is greater than the total number of samples (10). n_quantiles is set to n_samples.
  warnings.warn(


array([[0.91589196],
       [0.6092082 ],
       [0.91970834],
       [0.76298534],
       [0.91901373],
       [0.60500465],
       [0.60099795],
       [0.47525191],
       [0.49324026],
       [0.86907999]])

In [8]:
X_transformed

array([[0.77777778],
       [0.44444444],
       [1.        ],
       [0.55555556],
       [0.88888889],
       [0.33333333],
       [0.22222222],
       [0.        ],
       [0.11111111],
       [0.66666667]])

In [9]:
# KBinsDiscretizer (дискретизация признаков)
# Этот энкодер разбивает непрерывные данные на интервалы.
# Пример использования: если вам нужно проанализировать рынок потребления товаров в 
# зависимости от возраста покупателей, то KBinsDiscretizer поможет с группировкой возрастных данных по группам. 

from sklearn.preprocessing import KBinsDiscretizer
import numpy as np

X = np.array([[2.3], [5.6], [7.8], [1.2]])
est = KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')
est.fit(X)
transformed = est.transform(X)
X

/home/mle-user/.local/lib/python3.10/site-packages/sklearn/preprocessing/_discretization.py:248: FutureWarning: In version 1.5 onwards, subsample=200_000 will be used by default. Set subsample explicitly to silence this warning in the mean time. Set subsample=None to disable subsampling explicitly.
  warnings.warn(


array([[2.3],
       [5.6],
       [7.8],
       [1.2]])

In [10]:
transformed

array([[0.],
       [2.],
       [2.],
       [0.]])

In [14]:
# Задание 2
# Примените преобразования к вашим данным:
# Binarizer — к колонке income_usd (в качестве границы возьмите средние значения). Результат сохраните в 
#             колонку income_usd_binarized.
# StandardScaler — к колонке age_years. Результат сохраните в колонку age_years_standarded.
# LabelEncoder — к колонке is_subscribed. Результат сохраните в колонку is_subscribed_encoded.

import pandas as pd
import numpy as np
from datetime import timedelta
from sklearn.preprocessing import Binarizer, StandardScaler, LabelEncoder

np.random.seed(42)
np.random.default_rng(42)
# генерация данных для каждого столбца
data = {
    'temperature_celsius': np.random.uniform(20, 35, size=100),  # температура в градусах Цельсия (float)
    'age_years': np.random.randint(18, 65, size=100),  # возраст в годах (int)
    'timestamp_event': [pd.Timestamp('20230101') + timedelta(days=i) for i in range(100)],  # время события (datetime)
    'product_category': np.random.choice(['electronics', 'clothing', 'food'], size=100),  # категория продукта (string)
    'is_purchased': np.random.choice([True, False], size=100),  # булевое значение приобретения (bool)
    'humidity_percentage': np.random.uniform(40, 80, size=100),  # влажность в процентах (float)
    'income_usd': np.random.randint(20000, 100000, size=100),  # доход в долларах США (int)
    'last_updated': [pd.Timestamp('20240101') + timedelta(days=i) for i in range(100)],  # последнее обновление (datetime)
    'product_name': ['Product_' + str(i) for i in range(100)],  # название продукта (string)
    'is_subscribed': np.random.choice([True, False], size=100)  # булевое значение подписки (bool)
}

# создание DataFrame
df = pd.DataFrame(data)

In [15]:
# ваш код здесь #
df['income_usd_binarized'] = Binarizer(threshold=df['income_usd'].mean()).fit_transform(np.array(df['income_usd']).reshape(1, -1)).reshape(-1,1)
df['age_years_standarded'] = StandardScaler().fit_transform(np.array(df['age_years'].astype('float')).reshape(-1, 1)).reshape(-1,1)
df['is_subscribed_encoded'] = LabelEncoder().fit(df['is_subscribed']).transform(df['is_subscribed'])

In [16]:
df.head()

temperature_celsius  age_years timestamp_event product_category   
0            25.618102         49      2023-01-01      electronics  \
1            34.260715         56      2023-01-02      electronics   
2            30.979909         49      2023-01-03             food   
3            28.979877         21      2023-01-04         clothing   
4            22.340280         47      2023-01-05      electronics   

   is_purchased  humidity_percentage  income_usd last_updated product_name   
0          True            47.775201       75069   2024-01-01    Product_0  \
1          True            56.454156       34397   2024-01-02    Product_1   
2         False            67.980488       61555   2024-01-03    Product_2   
3          True            45.534124       66959   2024-01-04    Product_3   
4          True            45.309817       20728   2024-01-05    Product_4   

   is_subscribed  income_usd_binarized  age_years_standarded   
0          False                     1              0.648511  \
1           True                     0              1.166728   
2           True                     1              0.648511   
3           True                     1             -1.424355   
4           True                     0              0.500449   

   is_subscribed_encoded  
0                      0  
1                      1  
2                      1  
3                      1  
4                      1

In [17]:
# ИЛИ
df['income_usd_binarized'] = Binarizer(threshold=df['income_usd'].mean()).fit_transform(df[['income_usd']])
df['age_years_standarded'] = StandardScaler().fit_transform(df[['age_years']])
df['is_subscribed_encoded'] = LabelEncoder().fit(df['is_subscribed']).transform(df[['is_subscribed']])

/home/mle-user/.local/lib/python3.10/site-packages/sklearn/preprocessing/_label.py:132: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, dtype=self.classes_.dtype, warn=True)


In [18]:
df.head()

temperature_celsius  age_years timestamp_event product_category   
0            25.618102         49      2023-01-01      electronics  \
1            34.260715         56      2023-01-02      electronics   
2            30.979909         49      2023-01-03             food   
3            28.979877         21      2023-01-04         clothing   
4            22.340280         47      2023-01-05      electronics   

   is_purchased  humidity_percentage  income_usd last_updated product_name   
0          True            47.775201       75069   2024-01-01    Product_0  \
1          True            56.454156       34397   2024-01-02    Product_1   
2         False            67.980488       61555   2024-01-03    Product_2   
3          True            45.534124       66959   2024-01-04    Product_3   
4          True            45.309817       20728   2024-01-05    Product_4   

   is_subscribed  income_usd_binarized  age_years_standarded   
0          False                     1              0.648511  \
1           True                     0              1.166728   
2           True                     1              0.648511   
3           True                     1             -1.424355   
4           True                     0              0.500449   

   is_subscribed_encoded  
0                      0  
1                      1  
2                      1  
3                      1  
4                      1

In [19]:
# Пример как использовать ColumnTransformer, чтобы преобразовать данные перед моделированием 
# внутри одного Pipeline для метода опорных векторов (SVC).

from sklearn.svm import SVC
from sklearn.preprocessing import StandardScaler
from sklearn.datasets import make_classification
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.compose import ColumnTransformer

# генерация случайных данных
X, y = make_classification(random_state=0)
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

# определение числовых признаков для ColumnTransformer
numeric_features = [0, 1, 2, 3]  # пример числовых признаков (нумерация с 0)

# создание ColumnTransformer с преобразованиями для числовых признаков
preprocessor = ColumnTransformer(
    transformers=[
        ('num', StandardScaler(), numeric_features)  # преобразования для числовых признаков
    ])

# создание Pipeline с преобразованиями и моделью
pipe = Pipeline(steps=[('preprocessor', preprocessor),
                       ('classifier', SVC())])

# обучение модели
pipe.fit(X_train, y_train)

# оценка качества модели на тестовых данных
accuracy = pipe.score(X_test, y_test)
print(f"Accuracy: {accuracy}")

Accuracy: 0.88


In [20]:
# Задание 3
# Примените преобразования к вашим данным, используя объект ColumnTransformer внутри Pipeline. 
# Используйте преобразования из предыдущего задания:
#Binarizer — к колонке income_usd (в качестве границы возьмите средние значения),
#StandardScaler — к колонке age_years,
#OneHotEncoder — к колонке is_subscribed.

import pandas as pd
import numpy as np
from datetime import timedelta
from sklearn.preprocessing import Binarizer, StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline

np.random.seed(42)
np.random.default_rng(42)
# генерация данных для каждого столбца
data = {
    'temperature_celsius': np.random.uniform(20, 35, size=100),  # температура в градусах Цельсия (float)
    'age_years': np.random.randint(18, 65, size=100),  # возраст в годах (int)
    'timestamp_event': [pd.Timestamp('20230101') + timedelta(days=i) for i in range(100)],  # время события (datetime)
    'product_category': np.random.choice(['electronics', 'clothing', 'food'], size=100),  # категория продукта (string)
    'is_purchased': np.random.choice([True, False], size=100),  # булевое значение приобретения (bool)
    'humidity_percentage': np.random.uniform(40, 80, size=100),  # влажность в процентах (float)
    'income_usd': np.random.randint(20000, 100000, size=100),  # доход в долларах США (int)
    'last_updated': [pd.Timestamp('20240101') + timedelta(days=i) for i in range(100)],  # последнее обновление (datetime)
    'product_name': ['Product_' + str(i) for i in range(100)],  # название продукта (string)
    'is_subscribed': np.random.choice([True, False], size=100)  # булевое значение подписки (bool)
}

df = pd.DataFrame(data)

In [21]:
# создание ColumnTransformer с преобразованиями для различных колонок
preprocessor = ColumnTransformer(
    transformers=[
        ('income_usd', Binarizer(threshold=df['income_usd'].mean()), ['income_usd']),
        ('age_years', StandardScaler(), ['age_years']),
        ('is_subscribed', OneHotEncoder(), ['is_subscribed'])
        ]
    )# ваш код здесь #

# создание Pipeline с преобразованиями
pipe = Pipeline(steps=[('preprocessor', preprocessor)])# ваш код здесь #

transformed_data = pipe.fit_transform(df)# ваш код здесь #

In [24]:
transformed_data[:5]

array([[ 1.        ,  0.6485111 ,  1.        ,  0.        ],
       [ 0.        ,  1.16672773,  0.        ,  1.        ],
       [ 1.        ,  0.6485111 ,  0.        ,  1.        ],
       [ 1.        , -1.42435543,  0.        ,  1.        ],
       [ 0.        ,  0.50044921,  0.        ,  1.        ]])

In [27]:
# Рассмотрим и другие методы генерации признаков для временных данных, которые 
# значительно обогатят модель информацией.
# Извлечение признаков из даты:
# 1.Извлечение года, месяца, дня, дня недели, времени суток — эти признаки полезны для моделей, 
#   так как они могут содержат ценную информацию о сезонности, цикличности и динамике событий во времени.
#   Например, при анализе трат клиентов в онлайн-магазине вы можете извлечь месяц или день недели из даты 
#   покупки, чтобы определить, существует ли какая-либо зависимость между конкретными периодами времени и 
#   суммой покупок.
#
# 2.Расчёт временных интервалов:
#   Мы уже описали, почему разница между двумя датами — это потенциально полезный фактор. Однако здесь можно 
#   столкнуться с разрывом в данных. Если часть клиентов зарегистрировалась позже анализируемого периода, то 
#   информации о них не будет.
#
# 3.Скользящие окна и накопительные статистики:
#   Скользящие окна — расчёт статистики (например, среднее значение или сумма) по временным окнам (например, 
#   за предыдущие 7 дней).
#   Накопительные статистики — расчёт статистики на основе всей доступной исторической информации к определённому 
#   моменту времени. Например, сумма продаж на момент каждой новой транзакции.
#   Например, при анализе временных рядов, связанных с продажами, вы можете рассчитать скользящее среднее за 
#   последние 7 дней, чтобы оценить динамику.
#
# 4.Периодичность и тренды:
#   Можно рассматривать периодичность событий (сезонность продаж, повышенная активность в выходные дни). Можно 
#   использовать статистики или индикаторы, отражающие общий тренд в данных с течением времени.
#   Например, если вы анализируете данные по трафику на веб-сайте, то можете легко выделить тренды в поведении пользователей в различные дни недели или времена года.
# 5.Преобразование времени в категориальные признаки:
#   Преобразовать дату и время в категориальные признаки можно, например, с помощью OneHotEncoder или LabelEncoder.
#   Например, при анализе данных о производстве и распределении товаров вы можете закодировать месяц или квартал, чтобы выявить сезонные паттерны.
#   Ниже даны примеры для каждого из преобразований:

data = {
    'Random_Dates': [pd.Timestamp('20230101 11:25:25') + timedelta(days=i) for i in range(100)]
}

df = pd.DataFrame(data)

start_date = pd.Timestamp('20230101 01:01:01')
end_date = pd.Timestamp('20231201 01:01:01')
n_samples = 100

# 1. Извлечение признаков из даты
df['Year'] = df['Random_Dates'].dt.year
df['Month'] = df['Random_Dates'].dt.month
df['Day'] = df['Random_Dates'].dt.day
df['Weekday'] = df['Random_Dates'].dt.weekday
df['Hour'] = df['Random_Dates'].dt.hour

# 2. Расчёт временных интервалов (разница между двумя датами)
df['Date_2'] = pd.to_datetime(np.random.randint(start_date.value, end_date.value, n_samples))
df['Date_Difference'] = (df['Date_2'] - df['Random_Dates']).dt.days

# 3. Скользящие окна и накопительные статистики
rolling_mean = df['Date_Difference'].rolling(window=7).mean()
cumulative_sum = df['Date_Difference'].cumsum()

# 4. Периодичность и тренды
df['Trend'] = df['Random_Dates'].dt.month * np.random.rand(n_samples)  # пример генерации тренда
df['Season'] = df['Random_Dates'].dt.month % 4  # деление на 4 для сезонов (в качестве примера)

# 5. Преобразование времени в категориальные признаки с помощью OneHotEncoder
one_hot_encoder = OneHotEncoder(sparse_output=False, drop='first')
month_encoded = one_hot_encoder.fit_transform(df[['Month']])
columns = [f"Month_{month}" for month in one_hot_encoder.categories_[0][1:]]
month_encoded_df = pd.DataFrame(month_encoded, columns=columns) 

In [28]:
df.head()

Random_Dates  Year  Month  Day  Weekday  Hour   
0 2023-01-01 11:25:25  2023      1    1        6    11  \
1 2023-01-02 11:25:25  2023      1    2        0    11   
2 2023-01-03 11:25:25  2023      1    3        1    11   
3 2023-01-04 11:25:25  2023      1    4        2    11   
4 2023-01-05 11:25:25  2023      1    5        3    11   

                         Date_2  Date_Difference     Trend  Season  
0 2023-07-19 01:21:35.977887520              198  0.644000       1  
1 2023-02-25 02:51:34.674990045               53  0.408734       1  
2 2023-10-08 16:24:41.719858586              278  0.025386       1  
3 2023-11-14 16:47:55.105643164              314  0.156153       1  
4 2023-10-02 05:38:20.677398456              269  0.715972       1

In [29]:
one_hot_encoder

OneHotEncoder(drop='first', sparse_output=False)

In [31]:
month_encoded[:5]

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [32]:
month_encoded_df

Month_2  Month_3  Month_4
0       0.0      0.0      0.0
1       0.0      0.0      0.0
2       0.0      0.0      0.0
3       0.0      0.0      0.0
4       0.0      0.0      0.0
..      ...      ...      ...
95      0.0      0.0      1.0
96      0.0      0.0      1.0
97      0.0      0.0      1.0
98      0.0      0.0      1.0
99      0.0      0.0      1.0

[100 rows x 3 columns]

In [34]:
# Задание 4
# Вы работаете с данными о ежедневных температурах в градусах Цельсия за год в определённом 
# регионе. Ваша задача — предобработать временные данные, чтобы затем их можно было использовать 
# в модели машинного обучения. Выполните следующие шаги:
# - извлеките признаки из даты,
# - рассчитайте среднюю температуру за последние семь дней (скользящее окно) и накопительную сумму за весь период,
# - добавьте признаки, отражающие общий тренд в данных (сумма температур за каждый месяц) и периодичность 
#   событий (средняя температура по месяцам).

import pandas as pd
import numpy as np
from sklearn.preprocessing import OneHotEncoder

# генерация случайных данных о температурах за год
np.random.seed(42)
np.random.default_rng(42)
start_date = pd.Timestamp('2023-01-01')
end_date = pd.Timestamp('2023-12-31')
dates = pd.date_range(start=start_date, end=end_date)
temperatures = np.random.uniform(low=-10.0, high=30.0, size=len(dates))
temperature_data = pd.DataFrame({'Date': dates, 'Temperature_Celsius': temperatures})
temperature_data.head()

Date  Temperature_Celsius
0 2023-01-01             4.981605
1 2023-01-02            28.028572
2 2023-01-03            19.279758
3 2023-01-04            13.946339
4 2023-01-05            -3.759254

In [36]:
# 1. Извлечение признаков из даты
temperature_data['Month'] = temperature_data['Date'].dt.month
temperature_data['Weekday'] = temperature_data['Date'].dt.weekday
temperature_data['Hour'] = temperature_data['Date'].dt.hour
temperature_data.head()

Date  Temperature_Celsius  Month  Weekday  Hour
0 2023-01-01             4.981605      1        6     0
1 2023-01-02            28.028572      1        0     0
2 2023-01-03            19.279758      1        1     0
3 2023-01-04            13.946339      1        2     0
4 2023-01-05            -3.759254      1        3     0

In [38]:
# 2. Скользящие окна и накопительные статистики
temperature_data['Rolling_mean'] = temperature_data['Temperature_Celsius'].rolling(window=7).mean()
temperature_data['Cumulative_Sum'] = temperature_data['Temperature_Celsius'].cumsum()
temperature_data.head(15)

Date  Temperature_Celsius  Month  Weekday  Hour  Rolling_mean   
0  2023-01-01             4.981605      1        6     0           NaN  \
1  2023-01-02            28.028572      1        0     0           NaN   
2  2023-01-03            19.279758      1        1     0           NaN   
3  2023-01-04            13.946339      1        2     0           NaN   
4  2023-01-05            -3.759254      1        3     0           NaN   
5  2023-01-06            -3.760219      1        4     0           NaN   
6  2023-01-07            -7.676656      1        5     0      7.291449   
7  2023-01-08            24.647046      1        6     0     10.100798   
8  2023-01-09            14.044600      1        0     0      8.103088   
9  2023-01-10            18.322903      1        1     0      7.966394   
10 2023-01-11            -9.176620      1        2     0      4.663114   
11 2023-01-12            28.796394      1        3     0      9.313921   
12 2023-01-13            23.297706      1        4     0     13.179339   
13 2023-01-14            -1.506436      1        5     0     14.060799   
14 2023-01-15            -2.727001      1        6     0     10.150221   

    Cumulative_Sum  
0         4.981605  
1        33.010177  
2        52.289935  
3        66.236274  
4        62.477020  
5        58.716800  
6        51.040145  
7        75.687191  
8        89.731791  
9       108.054694  
10       98.878074  
11      127.674468  
12      150.972174  
13      149.465738  
14      146.738737

In [40]:
# 3. Периодичность и тренды
temperature_data['Monthly_Sum'] = temperature_data.groupby('Month')['Temperature_Celsius'].transform("sum")
temperature_data['Monthly_Mean'] = temperature_data.groupby('Month')['Temperature_Celsius'].transform("mean")
temperature_data.head(15)

Date  Temperature_Celsius  Month  Weekday  Hour  Rolling_mean   
0  2023-01-01             4.981605      1        6     0           NaN  \
1  2023-01-02            28.028572      1        0     0           NaN   
2  2023-01-03            19.279758      1        1     0           NaN   
3  2023-01-04            13.946339      1        2     0           NaN   
4  2023-01-05            -3.759254      1        3     0           NaN   
5  2023-01-06            -3.760219      1        4     0           NaN   
6  2023-01-07            -7.676656      1        5     0      7.291449   
7  2023-01-08            24.647046      1        6     0     10.100798   
8  2023-01-09            14.044600      1        0     0      8.103088   
9  2023-01-10            18.322903      1        1     0      7.966394   
10 2023-01-11            -9.176620      1        2     0      4.663114   
11 2023-01-12            28.796394      1        3     0      9.313921   
12 2023-01-13            23.297706      1        4     0     13.179339   
13 2023-01-14            -1.506436      1        5     0     14.060799   
14 2023-01-15            -2.727001      1        6     0     10.150221   

    Cumulative_Sum  Monthly_Sum  Monthly_Mean  
0         4.981605   240.618521      7.761888  
1        33.010177   240.618521      7.761888  
2        52.289935   240.618521      7.761888  
3        66.236274   240.618521      7.761888  
4        62.477020   240.618521      7.761888  
5        58.716800   240.618521      7.761888  
6        51.040145   240.618521      7.761888  
7        75.687191   240.618521      7.761888  
8        89.731791   240.618521      7.761888  
9       108.054694   240.618521      7.761888  
10       98.878074   240.618521      7.761888  
11      127.674468   240.618521      7.761888  
12      150.972174   240.618521      7.761888  
13      149.465738   240.618521      7.761888  
14      146.738737   240.618521      7.761888